### ISSUE TITLE
parabuzzle/craneoperator:latest    image V2, schema 1

### ISSUE THREAD

**Issue by raschidb** [digital-ai/release-integration-template-python#9]
Hello,

the crane operator docker image is in V2 schema 1 format wich is deprecated, last push on docker hub is  6 years ago.
I got this error on docker compose build :

[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/parabuzzle/craneoperator:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

Thank you
Rachid.

**Comment by balaji-digital-ai** [comment]
> Hello,
> 
> the crane operator docker image is in V2 schema 1 format wich is deprecated, last push on docker hub is 6 years ago. I got this error on docker compose build :
> 
> [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/parabuzzle/craneoperator:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
> 
> Thank you Rachid.

**Comment by balaji-digital-ai** [comment]
Hi, The issue was fixed with an alternate image.
